from .globals import DELIVERY_TYPES, PREORDER_STATUSES

PREORDER_STATUSES_CHOICES = (
    (PREORDER_STATUSES["APPROVED"], PREORDER_STATUSES["APPROVED"]),
    (PREORDER_STATUSES["PENDING"], PREORDER_STATUSES["PENDING"]),
    (PREORDER_STATUSES["DELIVERED"], PREORDER_STATUSES["DELIVERED"]),
    (PREORDER_STATUSES["CANCELLED"], PREORDER_STATUSES["CANCELLED"]),
)

DELIVERY_TYPES_CHOICES = (
    (DELIVERY_TYPES["PICKUP"], DELIVERY_TYPES["PICKUP"]),
    (DELIVERY_TYPES["DELIVERY"], DELIVERY_TYPES["DELIVERY"]),
)
