from .globals import BRANCH_PRODUCT_STATUSES


BRANCH_PRODUCT_STATUSES_CHOICES = (
    (BRANCH_PRODUCT_STATUSES["REORDER"], BRANCH_PRODUCT_STATUSES["REORDER"]),
    (BRANCH_PRODUCT_STATUSES["AVAILABLE"], BRANCH_PRODUCT_STATUSES["AVAILABLE"]),
    (BRANCH_PRODUCT_STATUSES["OUT_OF_STOCK"], BRANCH_PRODUCT_STATUSES["OUT_OF_STOCK"]),
)
