# Generated by Django 3.2.9 on 2021-11-24 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='branches.branchproduct')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
