# Generated by Django 3.2.9 on 2021-11-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_rename_delivered_out_by_delivery_delivered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
