# Generated by Django 3.2.9 on 2021-11-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_deliveryproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='datetime_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
