# Generated by Django 3.2.9 on 2022-02-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_delivery_datetime_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'unpaid'), ('paid', 'paid')], default='unpaid', max_length=20),
        ),
    ]
