# Generated by Django 3.2.9 on 2022-02-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_delivery_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('unpaid', 'unpaid'), ('paid', 'paid')], max_length=20, null=True),
        ),
    ]
