# Generated by Django 3.2.9 on 2022-04-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0006_alter_delivery_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_type',
            field=models.CharField(choices=[('market', 'market'), ('delivery', 'delivery'), ('pickup', 'pickup'), ('special', 'special')], max_length=20),
        ),
    ]
