# Generated by Django 3.2.9 on 2021-11-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='reorder_point',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
