# Generated by Django 3.2.9 on 2021-11-23 14:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('pickup', 'pickup'), ('delivery', 'delivery')], max_length=20)),
                ('status', models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], max_length=20)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'preorders',
            },
        ),
        migrations.CreateModel(
            name='PreorderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'preorder_products',
            },
        ),
        migrations.CreateModel(
            name='PreorderTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preorder_transactions', to='preorders.preorder')),
            ],
            options={
                'db_table': 'preorder_transactions',
            },
        ),
        migrations.CreateModel(
            name='PreorderTransactionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('preorder_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preorder_transaction_products', to='preorders.preorderproduct')),
                ('preorder_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preorder_transaction_products', to='preorders.preordertransaction')),
            ],
            options={
                'db_table': 'preorder_transaction_products',
            },
        ),
    ]
