# Generated by Django 3.2.9 on 2021-11-28 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('preorders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='datetime_fulfilled',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
