# Generated by Django 3.2.9 on 2021-11-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preorders', '0003_preorder_datetime_fulfilled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='datetime_fulfilled',
            field=models.DateTimeField(null=True),
        ),
    ]
