# Generated by Django 3.2.9 on 2021-11-28 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('preorders', '0004_alter_preorder_datetime_fulfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='preordertransaction',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
