# Generated by Django 3.2.9 on 2022-04-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preorders', '0007_alter_preorder_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorderproduct',
            name='remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
