# Generated by Django 3.2.9 on 2021-11-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("host", models.CharField(max_length=1000)),
                ("path", models.CharField(max_length=1000)),
                ("method", models.CharField(max_length=50)),
                ("uri", models.CharField(max_length=2000)),
                ("status_code", models.IntegerField()),
                ("get", models.TextField(blank=True, null=True)),
                ("post", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
