# Generated by Django 2.1.7 on 2021-02-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webrequest',
            name='cookies',
        ),
        migrations.RemoveField(
            model_name='webrequest',
            name='is_ajax',
        ),
        migrations.RemoveField(
            model_name='webrequest',
            name='is_secure',
        ),
        migrations.RemoveField(
            model_name='webrequest',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='webrequest',
            name='raw_post',
        ),
        migrations.RemoveField(
            model_name='webrequest',
            name='remote_addr',
        ),
        migrations.RemoveField(
            model_name='webrequest',
            name='remote_addr_fwd',
        ),
        migrations.RemoveField(
            model_name='webrequest',
            name='user_agent',
        ),
    ]
