# Generated by Django 3.2.9 on 2021-11-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_requests', '0002_auto_20210216_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
