from .globals import DELIVERY_TYPES, DELIVERY_STATUSES

DELIVERY_STATUSES_CHOICES = (
    (DELIVERY_STATUSES["PENDING"], DELIVERY_STATUSES["PENDING"]),
    (DELIVERY_STATUSES["DELIVERED"], DELIVERY_STATUSES["DELIVERED"]),
    (DELIVERY_STATUSES["CANCELLED"], DELIVERY_STATUSES["CANCELLED"]),
)

DELIVERY_TYPES_CHOICES = (
    (DELIVERY_TYPES["MARKET"], DELIVERY_TYPES["MARKET"]),
    (DELIVERY_TYPES["DELIVERY"], DELIVERY_TYPES["DELIVERY"]),
    (DELIVERY_TYPES["PICKUP"], DELIVERY_TYPES["PICKUP"]),
)
