# Generated by Django 3.2.9 on 2022-04-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_client_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_bakery',
            field=models.IntegerField(default=0),
        ),
    ]
