# Generated by Django 3.2.9 on 2022-04-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_client_is_bakery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_bakery',
            field=models.BooleanField(default=False),
        ),
    ]
